# Generated by Django 4.2.8 on 2026-03-03 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_subscriptionplan_usersubscription_recurringorder_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
